port: 3000
host: "localhost"
uploads:
  driver: "local" # you can change database driver here. 'local' or 'static' or 's3'
  local:
    path: "./uploads"
  static:
    serverPrefix: "/static"
    path: "/home/static/uploads"
  s3:
    bucket: "my-bucket"
    region: "eu-central-1"
    baseUrl: "http://docs-static.codex.so.s3-website.eu-central-1.amazonaws.com"
    keyPrefix: "/"
    accessKeyId: "my-access-key"
    secretAccessKey: "my-secret-key"
frontend:
  appName: "docs"
  basePath: "/docs"
  title: "Docs"
  description: "Docs app"
  startPage: ""
  misprintsChatId: "12344564"
  yandexMetrikaId: ""
  carbon:
    serve: ""
    placement: ""
  # menu:
  #   - "Guides"
  #   - title: "CodeX"
  #     uri: "https://codex.so"

auth:
  password: secretpassword
  secret: supersecret

hawk:
#  frontendToken: "123"
#  backendToken: "123"

database:
  driver: local # you can change database driver here. 'mongodb' or 'local'
  local:
    path: ./db
  # mongodb:
  #   uri: mongodb://localhost:27017/docs
